
## Edited by G.Perkins
## received copy from S. Parks Jan 16th 2025

# PLEASE DO NOT REDISTRIBUTE !!!
# PLEASE GAIN ACCESS TO LATEST CODE DIRECTLY FROM AUTHOR (IN CASE ANY MODIFICATIONS WERE MADE)

# Author: Sean Parks (sean.parks@usda.gov)
# Date: 12.20.2023

# Note there have been some minor updates to the original code described in the paper.
# Updated by Jared Balik (jbalik@western.edu) to use terra package instead of raster package
# Thanks to Benjamin Gannon and Quinn Barber for coding improvements.

# This is just a sample to get you started. You will need to modify to suit your needs.
# There is probably a lot of legacy/useless code here, but it works!

# Rationale for this procedure, validation of results, and comparison to 
# other interpolation methods can be found in (please cite this paper if you use this code): 
# Parks. 2014. Mapping day-of-burning with coarse-resolution satellite fire-detection data. International Journal of Wildland Fire. 23:215-223.

# DOB = day of burning

# I recommend you check the outputs to make sure the code is running as expected.

# Please don't make fun of my poor coding.


##########################################################################################################
# This code is divided into three stages.
# 1. This stage selects those MODIS and VIIRS fire detection points that will be used to model day of burning
#	# Simply put, this stage selects all fire detections within 1km of a final fire perimeter and deletes duplicate fire detections
# 2. This stage models day of burning
# 3. This stage removes small (<= 25 ha) 'regions' that are generated by the interpolation in stage 2
###########################################################################################################

rm(list=ls(all=T))

library(FNN)
library(timeDate)
library(terra)
library(igraph)
library(sf)
library(lubridate)
library(fs)

# This is a .gpkg of fire perimeters
fire.perims <- st_read(fs::path(spatialOutDir, "fires_perims_20102023bece.gpkg")) |> 
   filter(central_aoi == TRUE)
fire.perims <- st_transform(fire.perims, 4326)

# Year of fires. You will need to modify this file if you have several years to process
year <- 2018

# Set the output pixel size here. Canadian folk might want to consider 100 or 200 m.

pixel.size = 100

# set projection; this is the standard projection used by many national (USA) programs

the.prj <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"




#####################################################################################################################################################
#####################################################################################################################################################
# Stage 1 selects those fire detetections points that will be used to model day of burning (DOB) and write those points to a shapefile  #############
#																						                                                                                            #############
# NOTE THAT THIS CODE IS SPECIFIC TO FIRE DETECTION DATA OBTAINED FIRMS:										                                            #############
# https://firms.modaps.eosdis.nasa.gov/download/                                                               				                  #############
#																						                                                                                            #############
#####################################################################################################################################################
#####################################################################################################################################################

library(purrr)
## Get MODIS fire detections
#setwd('C:/temp/sample.DOB.code/sample.fire.detections/')

hs_dir <- fs::path("data", "spatial", "Hotspots","MODIS")
all_files <- list.files(hs_dir, recursive = TRUE)

purrr::map(all_files, function(x) {
  #x <- all_files[2]
  tfile <- read.csv(fs::path(hs_dir, x))
  tfile <- tfile[, c('latitude', 'longitude', 'acq_date', 'acq_time', 'satellite', 'instrument')]
  tsf <- st_as_sf(tfile, coords = c("longitude", "latitude"), crs = 4326)
  st_geometry(tsf) <- "geom"
  tsf_int <- st_intersects(tsf, fire.perims, sparse = FALSE)
  tsf_sub <- tsf[apply(tsf_int, 1, any),]
  tsf_sub
  #mapview::mapview(tsf_sub)
  
  }) |> bind_rows()





hotspots <- st_read(fs::path(hs_dir, paste0('fire_archive_M6_', year, '_subset.shp')))

#hotspots <- st_read('.', paste0('fire_archive_M6_', year, '_subset'))
hotspots <- hotspots[, c('LATITUDE', 'LONGITUDE', 'ACQ_DATE', 'ACQ_TIME', 'SATELLITE', 'INSTRUMENT')]

## Get VIIRS fire detections
if (year >= 2012) {
  #hotspots3 <- st_read('.', paste0('fire_archive_V1_', year, '_subset'))
  hotspots3 <- st_read(fs::path(hs_dir, paste0('fire_archive_V1_', year, '_subset.shp')))
  hotspots3 <- hotspots3[, c('LATITUDE', 'LONGITUDE', 'ACQ_DATE', 'ACQ_TIME', 'SATELLITE', 'INSTRUMENT')]
  hotspots <- rbind(hotspots, hotspots3) # Combine MODIS and VIIRS
}







